# Generated by Django 5.2 on 2025-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_collectionitem_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='thumbnail',
            field=models.CharField(),
        ),
    ]
