# Generated by Django 5.2 on 2025-04-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_collectionitem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie')], default='book'),
            preserve_default=False,
        ),
    ]
