# Generated by Django 5.2 on 2025-05-01 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_collectionitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='author',
        ),
    ]
